# Generated by Django 4.0.1 on 2022-06-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_joining', models.DateTimeField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('alternative_mobile_number', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=9)),
                ('spouse_name', models.CharField(max_length=50)),
                ('father_s_name', models.CharField(max_length=50)),
                ('mother_s_name', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=1000)),
                ('corresponding_address', models.CharField(max_length=1000)),
                ('physically_handicapped', models.CharField(max_length=3)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=6)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('upload_aadhar', models.ImageField(upload_to='uploads/')),
                ('pan_number', models.CharField(max_length=12)),
                ('upload_pan', models.ImageField(upload_to='uploads/')),
                ('bank_name', models.CharField(max_length=30)),
                ('confirm_bank_name', models.CharField(max_length=30)),
                ('bank_account_number', models.IntegerField()),
                ('confirm_bank_account_number', models.IntegerField()),
                ('bank_ifsc_code', models.CharField(max_length=12)),
                ('confirm_bank_ifsc_code', models.CharField(max_length=12)),
            ],
        ),
    ]
